"""
    ODL-Info API

    Daten zur radioaktiven Belastung in Deutschland. Weitere Informationen unter https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.strahlenschutz.model.geometry_point import GeometryPoint

from deutschland import strahlenschutz

globals()["GeometryPoint"] = GeometryPoint
from deutschland.strahlenschutz.model.base_feature import BaseFeature


class TestBaseFeature(unittest.TestCase):
    """BaseFeature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseFeature(self):
        """Test BaseFeature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseFeature()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
