"""
    ODL-Info API

    Daten zur radioaktiven Belastung in Deutschland. Weitere Informationen unter https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.strahlenschutz.model.base_schema import BaseSchema

from deutschland import strahlenschutz


class TestBaseSchema(unittest.TestCase):
    """BaseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseSchema(self):
        """Test BaseSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseSchema()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
