"""
    ODL-Info API

    Daten zur radioaktiven Belastung in Deutschland. Weitere Informationen unter https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.strahlenschutz.model.base_schema import BaseSchema
from deutschland.strahlenschutz.model.normal_feature import NormalFeature

from deutschland import strahlenschutz

globals()["BaseSchema"] = BaseSchema
globals()["NormalFeature"] = NormalFeature
from deutschland.strahlenschutz.model.normal_schema import NormalSchema


class TestNormalSchema(unittest.TestCase):
    """NormalSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormalSchema(self):
        """Test NormalSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NormalSchema()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
