"""
    ODL-Info API

    Daten zur radioaktiven Belastung in Deutschland. Weitere Informationen unter https://odlinfo.bfs.de/ODL/DE/service/datenschnittstelle/datenschnittstelle_node.html.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.strahlenschutz.model.base_schema import BaseSchema
from deutschland.strahlenschutz.model.extended_feature import ExtendedFeature

from deutschland import strahlenschutz

globals()["BaseSchema"] = BaseSchema
globals()["ExtendedFeature"] = ExtendedFeature
from deutschland.strahlenschutz.model.extended_schema import ExtendedSchema


class TestExtendedSchema(unittest.TestCase):
    """ExtendedSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtendedSchema(self):
        """Test ExtendedSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExtendedSchema()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
