on: [push, pull_request]
jobs:
  deutschland_generation:
    name: "Deutschland Generation"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7.8' ]
    steps:
      - uses: actions/checkout@v2

      # Create .spectral.yaml file used for linting
      - run: |
          echo "extends: spectral:oas" > .spectral.yaml

      # Runs a single command using the runners shell
      - name: "Lint file"
        uses: stoplightio/spectral-action@v0.8.1
        with:
            file_glob: "openapi.yaml"

      - name: "Generate deutschland code"
        uses: wirthual/deutschland-generator-action@latest
        with:
          openapi-file: ${{ github.workspace }}/openapi.yaml
          commit-to-git: true
          upload-to-pypi: false
          upload-to-testpypi: true
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          testpypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          python-version: ${{ matrix.python-version }}