on: [push, pull_request]
jobs:
    openapi_check:
      name: "OpenAPI check"
      runs-on: ubuntu-latest
      steps:
        - uses: nwestfall/openapi-action@v1.0.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            file: openapi.yaml
